### ISSUE TITLE
🥔🗜️✨ `Gizmo`: `Journal`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene-journal#1]
It would be nice to be able to publish short and long-form multi-media content

Supplants: Substack, Medium, Patreon

## Watering Hole

> i really wish substack wasn't funding people ideolgically committed to my community's extermination because i do ＊love＊ a good newsletter - [@NoraDotCodes](https://twitter.com/NoraDotCodes/status/1614857930708230145)

## Use Cases

- [x] zinc-collective/convene#1566
- [ ] zinc-collective/convene#1609
- [ ] zinc-collective/convene#1662
- [ ] zinc-collective/convene#1713
- [ ] Adding a Distribution Channel
  - [ ] Twitter
  - [ ] PRNewsWire?
  - [ ] GoodReads?
- [ ] Distributing Published Journal Entries
  - [ ] To Subscribers
  - [ ] To Distribution Channels
